In [3]:
import torch
torch.__version__

'1.13.1'

### Tensors

In [18]:
# random tensor
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(f"\nDatatype: {random_tensor.dtype}")
print(f"Size: {random_tensor.shape}")
print(f"Device: {random_tensor.device}")

tensor([[0.2153, 0.1042, 0.7301, 0.1600],
        [0.3948, 0.6089, 0.8017, 0.8257],
        [0.1762, 0.6580, 0.7371, 0.8158]])

Datatype: torch.float32
Size: torch.Size([3, 4])
Device: cpu


In [24]:
# operations
tensor = torch.tensor([1, 2, 3])
print(f"Add: {tensor + 10}")
print(f"Element wise mul: {tensor * 10}")
print(f"Sub: {tensor - 10}")
print(f"Division: {tensor / 10}")

Add: tensor([11, 12, 13])
Element wise mul: tensor([10, 20, 30])
Sub: tensor([-9, -8, -7])
Division: tensor([0.1000, 0.2000, 0.3000])


#### Reminder Notes on Matrices
* **Inner** dimensions must match
* Matrix will have the shape of **outer** dimensions
* Use transpose to make shapes match

In [32]:
# matrix mul
print(f"Element wise mul: {tensor * tensor}")
print(f"Matrix mul: {torch.matmul(tensor, tensor)}")
print(f"Matrix mul using '@': {tensor @ tensor}")

Element wise mul: tensor([1, 4, 9])
Matrix mul: 14
Matrix mul using '@': 14


In [41]:
# useful aggregation
a = torch.arange(0, 100, 10)
a.max(), a.min(), a.sum()

(tensor(90), tensor(0), tensor(450))

In [40]:
# mean (first changing Long type of tensor)
a.type(torch.float32).mean()

tensor(45.)

In [44]:
# positional max and min
a.argmax(), a.argmin()

(tensor(9), tensor(0))

#### Reshapng, stacking, squeezing and unsqueezing
* **reshaping**: reshapes and input tensor to a defined shape
* **view**: return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **stacking**: combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **squeeze**: removes all 1 dimensions from a tensor
* **unsqueeze**: add a 1 dimensions to a tensor
* **permute**: return a view of  the input with dimensions permuted (swapped) in a certain way

In [49]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
x.reshape(9, 1), x.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9]))

In [58]:
# same memory as x, changing z changes x too
z = x.view(9, 1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [61]:
# kind of concat in pandas
torch.stack([x, x], dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [64]:
x_squeeze = torch.squeeze(x.reshape(9, 1))
x_squeeze

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
x_squeeze.unsqueeze(dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
# permute, swap dims
x_reshape = x.reshape(9, 1)
x_reshape.permute(1, 0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])